import matplotlib.pyplot as plt
import numpy as np

def save(pathname, list):
    fileOpen = open(pathname, 'w')

    for i in range(len(list)):
        fileOpen.write(str(list[i]))
        fileOpen.write('\n')
    fileOpen.close()

def read(pathname, length):
    fileOpen = open(pathname, 'r')
    list = np.zeros(length)
    for i in range(length):
        list[i] = fileOpen.readline()
    return list

if __name__ == '__main__':
    '''x = np.arange(0, 10050, 50)
    l1 = read('reward_test_5_5_3_ED3_t2_nTU_obv3.txt', 201)
    l2 = read('reward_test_5_5_3_D3_3cen_nTU_obv3.txt', 201)
    l3 = read('reward_test_5_5_3_DQN_3cen_nTU_obv3.txt',201)'''
# 动态障碍物数量测试
    plt.figure(1, figsize=(7.125,5.6))
    x = np.arange(3, 9, 1)
    l1 = read('DRQN_CO_06012025_1_T2_OB_3UAVs_successrate.txt', 6)
    l2 = read('DRQN_05012025_T2_OB_3UAVs_successrate.txt', 6)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_OB_successrate.txt', 6)
    l4 = read('D3QN_24092024_T1_OB_successrate.txt', 6)
    plt.ylim(0.6, 1)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth = 3, markersize = '10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth = 3, markersize = '10')
    plt.legend(prop = {'family': 'Arial', 'size':16})
    plt.xticks(x[::1], size = 15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of moving obstacles', font)
    plt.ylabel('Success rate', font)
    plt.show()

    plt.figure(2,figsize=(7.125,5.6))
    x = np.arange(3, 9, 1)
    l1 = read('DRQN_CO_06012025_1_T2_OB_3UAVs_avgtime.txt', 6)
    l2 = read('DRQN_05012025_T2_OB_3UAVs_avgtime.txt', 6)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_OB_avgtime.txt', 6)
    l4 = read('D3QN_24092024_T1_OB_avgtime.txt', 6)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth=3, markersize='10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth=3, markersize='10')
    plt.ylim(230, 300)
    plt.legend(prop={'family': 'Arial', 'size': 16})
    plt.xticks(x[::1], size=15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of moving obstacles', font)
    plt.ylabel('Average time (s)', font)
    plt.show()

    plt.figure(3,figsize=(7.125,5.6))
    x = np.arange(3, 9, 1)
    l1 = read('DRQN_CO_06012025_1_T2_OB_3UAVs_TUserverate.txt', 6)
    l2 = read('DRQN_05012025_T2_OB_3UAVs_TUserverate.txt', 6)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_OB_TUserverate.txt', 6)
    l4 = read('D3QN_24092024_T1_OB_TUserverate.txt', 6)
    plt.ylim(0.95, 1)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth=3, markersize='10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth=3, markersize='10')
    plt.legend(prop={'family': 'Arial', 'size': 16})
    plt.xticks(x[::1], size=15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of moving obstacles', font)
    plt.ylabel('Data collection rate', font)
    plt.show()

    plt.figure(3,figsize=(7.125,5.6))
    x = np.arange(3, 9, 1)
    l1 = read('DRQN_CO_06012025_1_T2_OB_3UAVs_collision_rate.txt', 6)
    l2 = read('DRQN_05012025_T2_OB_3UAVs_collision_rate.txt', 6)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_OB_collision_rate.txt', 6)
    l4 = read('D3QN_24092024_T1_OB_collision_rate.txt', 6)
    plt.ylim(0, 0.1)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth=3, markersize='10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth=3, markersize='10')
    plt.legend(prop={'family': 'Arial', 'size': 16}, loc = 'upper left')
    plt.xticks(x[::1], size=15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of moving obstacles', font)
    plt.ylabel('Collision rate', font)
    plt.show()

# 节点数量测试
    plt.figure(1,figsize=(7.125,5.6))
    x = np.arange(9, 28, 3)
    l1 = read('DRQN_CO_06012025_1_T1_TU_3UAVs_successrate.txt', 7)
    l2 = read('DRQN_05012025_T1_TU_3UAVs_successrate.txt', 7)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_TU_successrate.txt', 7)
    l4 = read('D3QN_09012025_TU_T1_successrate.txt', 7)
    plt.ylim(0.5, 1)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth=3, markersize='10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth=3, markersize='10')
    plt.legend(prop={'family': 'Arial', 'size': 16})
    plt.xticks(x[::1], size=15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of IoT sensor nodes', font)
    plt.ylabel('Success rate', font)
    plt.show()

    plt.figure(2,figsize=(7.125,5.6))
    x = np.arange(9, 28, 3)
    l1 = read('DRQN_CO_06012025_1_T1_TU_3UAVs_avgtime.txt', 7)
    l2 = read('DRQN_05012025_T1_TU_3UAVs_avgtime.txt', 7)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_TU_avgtime.txt', 7)
    l4 = read('D3QN_09012025_TU_T1_avgtime.txt', 7)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth=3, markersize='10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth=3, markersize='10')
    plt.legend(prop={'family': 'Arial', 'size': 16})
    plt.xticks(x[::1], size=15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of IoT sensor nodes', font)
    plt.ylabel('Average time (s)', font)
    plt.show()

    plt.figure(3,figsize=(7.125,5.6))
    x = np.arange(9, 28, 3)
    l1 = read('DRQN_CO_06012025_1_T1_TU_3UAVs_TUserverate.txt', 7)
    l2 = read('DRQN_05012025_T1_TU_3UAVs_TUserverate.txt', 7)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_TU_TUserverate.txt', 7)
    l4 = read('D3QN_09012025_TU_T1_TUserverate.txt', 7)
    plt.ylim(0.95, 1)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth=3, markersize='10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth=3, markersize='10')
    plt.legend(prop={'family': 'Arial', 'size': 16})
    plt.xticks(x[::1], size=15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of IoT sensor nodes', font)
    plt.ylabel('Data collection rate', font)
    plt.show()

    plt.figure(3,figsize=(7.125,5.6))
    x = np.arange(9, 28, 3)
    l1 = read('DRQN_CO_06012025_1_T1_TU_3UAVs_collision_rate.txt', 7)
    l2 = read('DRQN_05012025_T1_TU_3UAVs_collision_rate.txt', 7)
    l3 = read('DuelingDQN_Centralized_07012025_1_T1_TU_collision_rate.txt', 7)
    l4 = read('D3QN_09012025_TU_T1_TUserverate.txt', 7)
    plt.ylim(0.01, 0.05)
    plt.plot(x, l1, 'd-', color='r', label='Improved-DRQN', linewidth=3, markersize='10')
    plt.plot(x, l2, '^-', color='g', label='DRQN', linewidth=3, markersize='10')
    plt.plot(x, l3, '*-', color='b', label='Centralized Dueling DQN', linewidth=3, markersize='13')
    plt.plot(x, l4, 'o-', color='m', label='D3QN', linewidth=3, markersize='10')
    plt.legend(prop={'family': 'Arial', 'size': 16})
    plt.xticks(x[::1], size=15)
    plt.yticks(size=15)
    plt.grid(True, linestyle='--', alpha=0.8)
    font = {'family': 'Arial', 'weight': 'normal', 'size': 20}
    plt.xlabel('Number of IoT sensor nodes', font)
    plt.ylabel('Collision rate', font)
    plt.show()

